title: Brayan Regino
email: brayanreginos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Brayan Regino # add your name
author-pic: adam-face.jpg
about-author: Estudiante de Ingeniería de Sistemas en la Universidad De La Costa CUC, 7to Semestre.

# Contact links
email: brayanreginos@gmail.com # Add your Email address
phone: 00 # Add your Phone number
website: brayanregino.ml # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: breggino # Add your Github handle
twitter: '' # Add your Twitter handle
facebook: BrayanRgn # Add your Facebook handle
instagram: Brayanregino_ # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier:  # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
